spring:
  datasource:
    # localhost - Windows/IntelliJ uchun, 172.17.0.1 - WSL uchun
    url: jdbc:postgresql://${DB_HOST:localhost}:5432/family_finance_db
    username: family_finance_user
    password: ${DB_PASSWORD:family_finance_2026}
    driver-class-name: org.postgresql.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate

  # Vault va Cloud tekshiruvlarini dev muhitda o'chirish
  cloud:
    vault:
      enabled: false
    compatibility-verifier:
      enabled: false

logging:
  level:
    uz.familyfinance: DEBUG
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG
