spring:
  application:
    name: family-finance-api

  profiles:
    active: dev

  # Timezone - Toshkent vaqti
  jackson:
    time-zone: Asia/Tashkent
    date-format: yyyy-MM-dd HH:mm:ss

  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_batch_fetch_size: 16
        jdbc:
          time_zone: Asia/Tashkent

  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration

server:
  port: 8098
  servlet:
    context-path: /api

# JWT Configuration
jwt:
  secret: ${JWT_SECRET:xnhjaEEX34DyNFfL44YWX3kDuQNj4xxhb1jZ6SEESCrAoAyXAAXIl1IPCNPT0N3fyBXmdyBg6Gj4GLSz+hiGkg==}
  expiration: 3600000 # 1 hour in milliseconds
  refresh-expiration: 86400000 # 1 day

# Swagger/OpenAPI
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method

# Card Encryption
app:
  card-encryption:
    key: ${CARD_ENCRYPTION_KEY:acf5854e4ece6429894b227aeaaecbeb}

# Logging
logging:
  level:
    root: INFO
    uz.familyfinance: DEBUG
    org.springframework.security: DEBUG
    org.springframework.security.web.access: DEBUG
    org.springframework.security.access: DEBUG
