spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:db}:5432/${DB_NAME:family_finance_db}
    username: ${DB_USERNAME:family_finance_user}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    show-sql: false
    hibernate:
      ddl-auto: validate

  # Vault va Cloud tekshiruvlarini production da o'chirish
  cloud:
    vault:
      enabled: false
    compatibility-verifier:
      enabled: false

logging:
  level:
    root: INFO
    uz.familyfinance: INFO
    org.springframework.security: WARN
    org.hibernate.SQL: WARN
